### ISSUE TITLE
status / direction of library

### ISSUE THREAD

**Issue by jonschoning** [cmahon/interactive-brokers#6]
I noticed that Builder.hs only provides 2 functions, one for futures & one for market orders.  

Is this library also geared to be used for stock securities, or will it simply only target forex & currencies?

The readme says it's a work in progress.  Is there any plans to finish the library?

I am curious if i should implement my own library; it seems I'm interested in different features.

**Comment by cmahon** [comment]
Hi Jon,

I intended to provide support for all the main financial instruments, including stocks, but only got round to implementing a couple of helper functions as part of my initial testing efforts. I don't have any immediate plans to revive work on the library but may well do so in the months ahead - can't guarantee anything though.

What features are you interested in implementing?

Chris
